### ISSUE TITLE
"Unknown error" appears once more.

### ISSUE THREAD

**Issue by SalvaZaraes** [Malopieds/InnerTune#415] opened 2024-11-28 09:33 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Play any song
2. "Unknown error" appears.

### Expected behavior

To play any song.

### Actual behavior

Gives the unknown error message.

### Logs

.

### InnerTune version

0.5.11

### Android version

Android 15

**Comment by Malopieds** [comment] 2024-11-28 09:34
Duplicate of #410

**Closed as completed by Malopieds** 2024-11-28 09:34 UTC
Labels: bug
