### ISSUE TITLE
feature to user tag tracks 

### ISSUE THREAD

**Issue by zettaexa** [Malopieds/InnerTune#343] opened 2024-08-24 04:20 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

a feature to let the user add information onto a track such as cover art, name, and artist , would be stored locally on device

### Why do you want this feature?

would be great for scrobbling non-yt music tracks since pano scrobbler puts the artist name as the uploader of the song rather than the artist themselves (like in youtube)

also i believe apple music has this feature too, this was my inspiration for this request

### Additional information

if you are planning to do this feature anytime make sure its a part of the overflow menu of the player + an option to multi select different tracks as in a playlist or album

**Comment by Malopieds** [comment] 2024-08-24 06:36
> the overflow menu of the player

What do you mean by that? The menu after clicking on the 3 dots?

> an option to multi select different tracks as in a playlist or album

I'll see how I implement it first.

But I think this is a duplicate of #115, reopen if I'm mistaking.

**Closed as completed by Malopieds** 2024-08-24 06:36 UTC
Labels: enhancement
