### ISSUE TITLE
New songs added don't appear all the way to top 

### ISSUE THREAD

**Issue by Ikari115** [Malopieds/InnerTune#165] opened 2024-07-04 06:01 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Add to Favorites or playlist
Order of songs: Date Added
Play the added song and search for it in the list of selections, it will appear at the bottom instead of at the top

### Expected behavior

When you add a new song to favorites, it should rank at the top of the selection

### Actual behavior

On the contrary, it is usually randomly positioned at the bottom

### Screenshots/Screen recordings

![Screenshot_2024-07-03-23-53-09-054_com malopieds innertune-edit](https://github.com/Malopieds/InnerTune/assets/148160950/7bf1531c-c925-4a99-9549-09aa1048f357)

### Logs

*

### InnerTune version

0.5.7

### Android version

Android 14

### Additional information

In beta version 0.5.7-rc-2 this did not happen

**Comment by Malopieds** [comment] 2024-07-04 06:02
Duplicate of #160

**Closed as completed by Malopieds** 2024-07-04 06:02 UTC
Labels: bug
