### ISSUE TITLE
The sorting process in the downloaded playlist is not working

### ISSUE THREAD

**Issue by moaxaxx** [Malopieds/InnerTune#369] opened 2024-10-26 15:42 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

go to library and open downloaded auto playlist 

### Expected behavior

 It should be sorted by date or names.

### Actual behavior

 This never happens

### Screenshots/Screen recordings

> 

### Logs

> 

### InnerTune version

debug

### Android version

android 14

### Additional information

Sorting is very important in lists to make them more organized, and I hope it can be fixed in the next update, if possible. Thank you

**Comment by Malopieds** [comment] 2024-11-02 15:45
Duplicate of #142

**Closed as completed by Malopieds** 2024-11-02 15:45 UTC
Labels: bug
