### ISSUE TITLE
Fix the header when we search song

### ISSUE THREAD

**Issue by budisundae** [Malopieds/InnerTune#254] opened 2024-07-23 01:42 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Right now, when we scroll through the song we've searched, i get a little bit annoyed with fact that the header will be went through by the song list. 

Please fix it with add for example a solid background to the header :) thank you so much
![Screenshot_20240723-093656_InnerTune](https://github.com/user-attachments/assets/0ccb83c9-5072-4838-88f3-ed091e7cf804)

### Why do you want this feature?

This will make innertune a much more perfect app

**Comment by Malopieds** [comment] 2024-07-23 05:59
Duplicate of #26

**Closed as completed by Malopieds** 2024-07-23 05:59 UTC
Labels: enhancement
