### ISSUE TITLE
Playlists doesn't download

### ISSUE THREAD

**Issue by Lorestan00** [Malopieds/InnerTune#83] opened 2024-04-27 19:04 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Go to library
Open playlist 
Click download

### Expected behavior

Playlist should download 

### Actual behavior

but keeps showing spinning download icon 

I've force stopped the app but makes no difference 

Behaviour is mirrored by other playlists too

On version 0.56 

### Logs

How do I find this? Can't see an option in the app for logs

### InnerTune version

0.56

### Android version

14

**Comment by Malopieds** [comment] 2024-04-28 13:44
Hi,
I cannot reproduce it, does it happens only to playlists or also to albums ?

**Comment by Lorestan00** [comment] 2024-04-28 19:39
I had only seen the issue with playlists. I actually just downloaded an album to see if it was impacted as well and the playlists have now downloaded. Not sure if there was a stuck for some reason in a queue. 

One thing can you delete playlists or manually arrange them?

**Comment by Malopieds** [comment] 2024-08-23 06:21
> One thing can you delete playlists or manually arrange them?

You can delete them by long clicking on it then delete. You cannot manually arrange them.

So if I understand it doesn't happens anymore ?

**Comment by Lorestan00** [comment] 2024-08-23 08:03
Thanks yep deleting playlists works great

**Comment by Malopieds** [comment] 2024-08-23 08:12
Cool, I'm closing it then.

**Closed as completed by Malopieds** 2024-08-23 08:12 UTC
Labels: bug, can't reproduce
