### ISSUE TITLE
Spelling mistake 

### ISSUE THREAD

**Issue by Dawimpy** [Malopieds/InnerTune#268] opened 2024-07-28 06:45 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Go to settings and click on about

It should be "forked by" instead of "fork my"

### Expected behavior

.

### Actual behavior

.

### Screenshots/Screen recordings

![Screenshot_2024-07-28-14-43-27-965_com malopieds innertune](https://github.com/user-attachments/assets/d2aaecd9-c454-4e57-8433-adf6b82650fc)

### Logs

.

### InnerTune version

0.5.8

### Android version

Android 14

**Comment by Malopieds** [comment] 2024-07-28 06:46
Duplicate of #246

**Closed as completed by Malopieds** 2024-07-28 06:46 UTC
Labels: bug
