### ISSUE TITLE
No stream available.

### ISSUE THREAD

**Issue by Hikari2w2** [Malopieds/InnerTune#178] opened 2024-07-08 05:42 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

- Play a song
- Sometimes this song won't reproduce, getting this message instead "stream no available"

### Expected behavior

- Play a song
- reproduce the song
![Screenshot_2024-07-08-01-41-02-904_app rvx android apps youtube music](https://github.com/Malopieds/InnerTune/assets/124070334/4cc0d729-4cfc-487e-8828-e10e13e5a540)

### Actual behavior

- play a song
- it's not reproducing the song, instead it's getting an error (No stream available)

### Screenshots/Screen recordings

![Screenshot_2024-07-08-01-30-10-956_com malopieds innertune](https://github.com/Malopieds/InnerTune/assets/124070334/addda2e9-f1c5-44d7-ac46-9c666134f0cd)

### Logs

I don't know how to do that

### InnerTune version

0.5.7

### Android version

11

### Additional information

I used to be able to reproduce this song a few weeks before updating the app

**Comment by Malopieds** [comment] 2024-07-08 05:46
It plays fine for me. What is the id of the song (check in both YouTube and YouTube music)? Backup and restore the database.

**Comment by Hikari2w2** [comment] 2024-07-08 15:15
> It plays fine for me. What is the id of the song (check in both YouTube and YouTube music)? Backup and restore the database.

![Screenshot_2024-07-08-11-11-54-281_com.malopieds.innertune.jpg](https://github.com/Malopieds/InnerTune/assets/124070334/4ce98478-a15d-4cab-8e32-8b59bee4eadc)

This is the ID song, I checked the song on yt music, and it's playing properly, it might be a bug from my app, I'll try to backup and restore the database, thanks for your reply.

**Comment by Malopieds** [comment] 2024-07-10 09:03
My guess is that you played it from a playlist? Try to play it from an online search and after this try to play it from the playlist. I might have understood why.

**Comment by malisipi** [comment] 2024-07-11 01:14
I can reproduce the bug. When you encounter a rate limit of YouTube, YouTube will give no stream (or invalid streams). And the InnerTube will cache the invalid state and will show a warning about no stream every try.

To reproduce it, you may try to download a lot of playlists that have a lot of songs (and ensure the songs are not cached) and some songs would not be downloaded due to the rate limit. And you should be able to reproduce the issue.

Also clearing song/cover cache is not fixing the bug. Since I need to lose my downloaded song, I cannot try to reset the InnerTune.

It is also related to https://github.com/Malopieds/InnerTune/issues/170 . Since those songs throw no stream always, those songs cannot download or play on the application.

Also I think it is also related with https://github.com/Malopieds/InnerTune/issues/174 and https://github.com/Malopieds/InnerTune/issues/83 .

Lastly, I thank you for your efforts. ❤️

**Comment by Hikari2w2** [comment] 2024-07-11 01:36
> My guess is that you played it from a playlist? Try to play it from an online search and after this try to play it from the playlist. I might have understood why.

Hey, thank you for you reply. i tried by playing my song from link instead of playlist but my issue wasn't solved.

I tried resetting Innertune from scratch with no backup and downloading-playing my songs, and that worked - I was able to reproduce my songs. However, things went wrong when I imported my Innertune backup again. After importing the backup, some songs just won't reproduce or download at all. I've tried clearing the cache, downloads, and image cache, but that hasn't solved the problem. 

I think my backup might be corrupted or something, but I really don't want to lose my history and likes. I hope i was able to convey my issue, since my English is not very good.

**Comment by darumanzane** [comment] 2024-07-11 20:31
Adding to all that, I realized that songs with explicit tittles will present a similar issue.
I made a playlist to track which songs aren't available, and a lot of them have similar explicit words in them.

![Screenshot_2024-07-11-15-28-52-445_com zionhuang music](https://github.com/user-attachments/assets/928b637c-56fc-42db-8390-daad853d2308)

**Comment by malisipi** [comment] 2024-07-11 21:17
> Adding to all that, I realized that songs with explicit tittles will present a similar issue. I made a playlist to track which songs aren't available, and a lot of them have similar explicit words in them.

I tested some of songs and i get same error exactly. The songs can not be played or downloaded. However the songs is not throwing "no streams available" bug. Player is awaiting forever.

**Comment by darumanzane** [comment] 2024-07-12 06:32
Yes! I've noticed is a different kind of error, but with the same result (not available to play or download). Some songs just keep loading until it fails and shows the red icon.

However, is remarkable that this kind of "error song" behaves differently than the "no stream available song", since the later never seems to change. On the contrary, the "error song" can be played and eventually downloaded if you keep coming back to it and try again. Don't know how or why it works if you keep coming back to it, but in some cases it works.

**Comment by Malopieds** [comment] 2024-07-12 08:36
Could anyone provide a backup with a reproducible no stream available?

**Comment by darumanzane** [comment] 2024-07-12 12:57
I have a backup with that playlist I mentioned earlier. It was made in the v0.5.6, btw.

[InnerTune_11julio2024.zip](https://github.com/user-attachments/files/16194369/InnerTune_11julio2024.zip)

Some songs are consistently not available, regardless of the version of the app. But there's other songs that present the issue randomly.

The only way I have managed to fix them is creating a backup, uninstalling the app, install it again and downloading the "no stream available songs" before restoring the backup. But that doesn't fix the problem at is core, since everytime I re-install the app, new songs present the issue at random, plus I have to (try) download or play every single song again, which is sush a time consuming task, and the bigger the library, the more impractical this non-fix results.

**Comment by d4f5409d** [comment] 2024-07-12 16:00
Same issue here v0.5.7

**Comment by Hikari2w2** [comment] 2024-07-12 16:01
> Could anyone provide a backup with a reproducible no stream available?

I can also provide my backup, however my backup contains my google account information, so, i can share my backup if you provide me an email address only.

**Comment by anxiouslelimo** [comment] 2024-07-19 12:14
@Malopieds https://github.com/Malopieds/InnerTune/issues/87#issuecomment-2118665632 backup for a similar issue.

**Comment by Malopieds** [comment] 2024-08-23 07:06
Hi all, I've made a debug version, it includes a try fix for this issue, could anyone [try](https://github.com/Malopieds/InnerTune/actions/runs/10515383118/artifacts/1844333695) it and tell me?

>  I made a playlist to track which songs aren't available, and a lot of them have similar explicit words in them.

Related to #174 rather than this issue

**Comment by darumanzane** [comment] 2024-08-23 12:19
Hi. I just tried it and it kinda worked: only 6 of 45 songs of the playlist I have for this issue actually downloaded. These are the ones:
![IMG-20240823-WA0000](https://github.com/user-attachments/assets/01fc3b84-13bf-4139-a15e-02ee5b347607)
The 39 remaining songs still present the same issue. Just to clarify: I did use a backup of my most recent data (created in the v0.5.9), don't know if that is a relevant factor for any of this.

**Comment by Malopieds** [comment] 2024-08-23 12:30
Those songs are age restricted you should not be able to download them actually. Are you logged in? My question was do you still have the issue "No stream available"? If no I close this issue. There is already another issue about downloading songs that doesn't work.

**Comment by darumanzane** [comment] 2024-08-23 14:00
I don't know how to differentiate between "age restricted songs" and "no stream available songs", cause both types show the same text.
In any case, of those 39 songs only around half got explicit tittles, so I guess the rest are the "no stream available" type and still doesn't work.
I'm not logged in. Does that fix something?
Also, can you share the other issue related to this one? thankyou

**Comment by Malopieds** [comment] 2024-08-23 14:03
> I don't know how to differentiate between "age restricted songs" and "no stream available songs", cause both types show the same text.

No they don't. No stream available show "No stream available" and age restricted songs show "Unknown error".

> so I guess the rest are the "no stream available" type and still doesn't work.

Can you click on them and show me what happens?

>  I'm not logged in. Does that fix something?

No.

> Also, can you share the other issue related to this one? thankyou

#170

**Comment by Hikari2w2** [comment] 2024-08-23 18:18
Hi 👋, I've just tried the debug version and tested it out by playing a bunch of my songs with backup imported, they seem to be playing properly, so that's a good sign, also I'm not getting "no stream available" error anymore.

At first i wasn't able to play almost any song, since i was getting a weird new java error, but i was able to fix this issue by using VPN. Thank you for being so thoughtful about this issue.

Note: this is the java error i was getting without vpn ![Screenshot_2024-08-23-12-44-03-625_com.malopieds.innertune.debug.jpg](https://github.com/user-attachments/assets/86371adf-5d17-42f7-a864-a927c917c3bf)

**Comment by Malopieds** [comment] 2024-08-23 20:34
Cool for this issue, I'll close it then. On the other hand for the second issue, it's weird, I've never seen it, but glad it was only temporary!

**Closed as completed** 2024-08-23 20:34 UTC
Labels: bug

**Comment by d4f5409d** [comment] 2024-08-25 09:52
@Malopieds I have quite an idea, let's create an issue for improving the gradient function! You could use an animation to make the gradient change smoother, it'd make the experience better and the latency (because of the loading of the thumbnail) less noticeable. But you could also try to prefetch, a low quality version of the upcoming songs' thumbnails to be able to destroy the whole latency between switching songs and loading the correct gradient.

**Comment by Malopieds** [comment] 2024-08-25 09:55
> @Malopieds I have quite an idea, let's create an issue for improving the gradient function! You could use an animation to make the gradient change smoother, it'd make tge experience better and the latency (because of the loading of the thumbnail) less noticeable. But you could also try to prefetch, a low quality version of the upcoming songs' thumbnails to be able to destroy the whole latency between switching songs and loading the correct gradient.

#210

**Comment by darumanzane** [comment] 2024-08-25 11:35
> Can you click on them and show me what happens?

Sure, here's some screenshots:
![IMG-20240825-WA0001](https://github.com/user-attachments/assets/b039a11a-4900-452f-b319-d8b42c7dbd78)
![IMG-20240825-WA0000](https://github.com/user-attachments/assets/ece657b3-355c-4062-9de9-8553e9a5ab91)
![IMG-20240825-WA0002](https://github.com/user-attachments/assets/d35633e2-8761-46ce-9cc9-045721405929)
![IMG-20240825-WA0003](https://github.com/user-attachments/assets/15c49d91-5f40-4a33-ad0b-59ea5b10b13c)

Maybe in Spanish the text is the same, because I've never seen a variant of the error.
