### ISSUE TITLE
Multiple entries for the same song in history

### ISSUE THREAD

**Issue by W1zardK1ng** [Malopieds/InnerTune#35] opened 2024-04-01 02:24 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Play a song multiple times, may be play the song by enabling the repeat option.

### Expected behavior

One song should show only one entry in history for a day, even though it was played multiple times.
Only the position should be moved up or down if there is any another song played in between.

### Actual behavior

For each time one song is played the history section adds one entry. This make the history section filled with only one song name when played a song in loop.

### Logs

na

### InnerTune version

0.5.5

### Android version

Android 14

**Comment by Malopieds** [comment] 2024-04-01 17:36
Will be fixed in the next release !

**Closed as completed** 2024-04-01 17:36 UTC
Labels: bug

**Comment by blindman81** [comment] 2024-08-22 11:32
> Will be fixed in the next release !

This bug is still present.
![Screenshot_2024-08-22-16-58-55-27_56635af9b6ad4512d4187a5a49185a25](https://github.com/user-attachments/assets/931e2871-f157-427f-b8a8-653b4e811266)

https://github.com/z-huang/InnerTune/commit/b6e3c3ddeeb703eb7dc169f04763377b5f04670a

**Comment by Malopieds** [comment] 2024-08-22 11:36
> This bug is still present.

Can't reproduce, how did you reproduced it?

**Comment by blindman81** [comment] 2024-08-22 12:17
> > This bug is still present.
> 
> Can't reproduce, how did you reproduced it?

I just played a song from the library two times and it showed duplicates. I thought maybe the problem was with the library, so then i played a song from new releases two times again but still it showed duplicates. 

I am on the stable 0.5.9 build.

**Comment by iLikeCake10** [comment] 2024-08-22 12:37
This is the behaviour on the latest debug build

https://github.com/user-attachments/assets/2f40dc54-301d-4d31-bbaa-e1d7ff102ac4

**Comment by blindman81** [comment] 2024-08-23 13:17
> > This bug is still present.
> 
> Can't reproduce, how did you reproduced it?

Can you implement this?
https://github.com/z-huang/InnerTune/commit/12016e619b549426e53309f05c28b214d5f36ede

**Comment by Malopieds** [comment] 2024-08-23 16:08
Done
