### ISSUE TITLE
Songs not playing 

### ISSUE THREAD

**Issue by vedantanna** [Malopieds/InnerTune#435] opened 2024-12-17 15:01 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Play any song.

### Expected behavior

Song should play 

### Actual behavior

This action is not supported 

### Logs

Don't know 

### InnerTune version

0.5.12

### Android version

Android 14

**Comment by Malopieds** [comment] 2024-12-17 15:02
Duplicate of #433

**Closed as not planned** 2024-12-17 15:02 UTC
Labels: bug

**Comment by Hikari2w2** [comment] 2024-12-17 15:33
Same problem, cant play any song, no fork is working rn

**Comment by MizxGaming** [comment] 2024-12-18 02:17
Many invidious instances also stopped working over the course of the last 4-5 months. 

Is this some coincidence or is YouTube just being an arsehole? Also if possible to solve this somehow, is it being worked on currently (InnerTune)?
