### ISSUE TITLE
Songs not playing/downloading

### ISSUE THREAD

**Issue by Irobrine** [Malopieds/InnerTune#418] opened 2024-11-29 00:00 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Try to play any song that is not downloaded, or try to download any song.

### Expected behavior

Somg should play/download

### Actual behavior

Stalls at 0 then skips to the next song (which then stalls again and then skips to the next song, repeats) / songs do not download

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/41209c1b-3a89-4ded-9095-0408a46d2146

https://github.com/user-attachments/assets/e5c8dd41-1457-4231-9586-9ad8346b3208

### Logs

can't provide atm

### InnerTune version

0.5.12

### Android version

Android 14

### Additional information

pretty sure the two issues are linked

**Comment by mikedizhur** [comment] 2024-11-29 02:47
Second this.

[28_11-21-37-18_945.log](https://github.com/user-attachments/files/17953732/28_11-21-37-18_945.log)

Log using latest debug build, logged in. The issue persists while logged out.

Surprisingly, works on 5.9 when logged in. (As suggested on a different issue?)

**Comment by JosephM101** [comment] 2024-11-29 04:42
Same here. Attempting to stream/download gives me "Unknown error"

![Screenshot_20241128-234111](https://github.com/user-attachments/assets/788a89f3-d8d7-402d-9ffe-38bb1494c1aa)

**Comment by watashinosoulsociety** [comment] 2024-11-29 05:03
> Same here. Attempting to stream/download gives me "Unknown error"
> 
> ![Screenshot_20241128-234111](https://github.com/user-attachments/assets/788a89f3-d8d7-402d-9ffe-38bb1494c1aa)
> 

Happens with me as well

**Comment by ghost** [comment] 2024-11-29 05:41
Can confirm this is happening to me too.

**Comment by PupPuck** [comment] 2024-11-29 06:00
I can confirm it's happening to me as well. :(

**Comment by Malopieds** [comment] 2024-11-29 07:06
Duplicate of #410

**Closed as completed by Malopieds** 2024-11-29 07:06 UTC
Labels: bug
