### ISSUE TITLE
Force Album Art to square

### ISSUE THREAD

**Issue by tomxposed** [Malopieds/InnerTune#301] opened 2024-08-13 12:30 UTC
### Checklist

- [ ] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Most album arts are rectangular. It would look nice if you cropped them into squares or blurred the top and bottom to make them square.

### Why do you want this feature?

The UI would look more aesthetically pleasing and uniform without unwanted negative space.

**Comment by Malopieds** [comment] 2024-08-13 12:36
They are square? I don't understand, could you provide images?

**Comment by Spaceshiprace** [comment] 2024-08-13 13:51
@Malopieds 
regarding the videos can make thier thumbnails square cuz they're actually rectangular and also thier thumbnails are blurred a bit despite the thumbnails on yt

**Comment by Malopieds** [comment] 2024-08-13 13:52
So duplicate of #219

**Closed as completed by Malopieds** 2024-08-13 13:52 UTC
Labels: enhancement

**Comment by tomxposed** [comment] 2024-08-13 15:11
![Screenshot_20240813_203851_InnerTune](https://github.com/user-attachments/assets/24c04cdf-2d27-43d7-bfe9-cf499bc4d431)

**Comment by tomxposed** [comment] 2024-08-13 15:19
> @Malopieds regarding the videos can make thier thumbnails square cuz they're actually rectangular and also thier thumbnails are blurred a bit despite the thumbnails on yt

Can we load the rectangle images inside the square and add a blur on the top and the bottom parts of the image view. Eg:
![page1](https://github.com/user-attachments/assets/aef7fedd-165b-4f66-ac11-1fbc4a60867e)

**Comment by Spaceshiprace** [comment] 2024-08-13 18:43
> > @Malopieds regarding the videos can make thier thumbnails square cuz they're actually rectangular and also thier thumbnails are blurred a bit despite the thumbnails on yt
> 
> Can we load the rectangle images inside the square and add a blur on the top and the bottom parts of the image view. Eg: ![page1](https://private-user-images.githubusercontent.com/32647796/357470184-aef7fedd-165b-4f66-ac11-1fbc4a60867e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NzQ2OTYsIm5iZiI6MTcyMzU3NDM5NiwicGF0aCI6Ii8zMjY0Nzc5Ni8zNTc0NzAxODQtYWVmN2ZlZGQtMTY1Yi00ZjY2LWFjMTEtMWZiYzRhNjA4NjdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDE4Mzk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwNzJhZmU1N2YzMTViMmIyMGI1YmZiNGM1NmVhMDVjMmM2YmNlMjUzOTAzYTA1MzhhYWZjMThjNDg0NjA2NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s9U-Bbygz8sQktf4r5ajt5flwB0DqbTDcw93vBjfgfg)

nice idea that will make the thumbnails appear fully, but i don't like that idea of adding that blur instead of it I would rather like it to be just pure black on the top and bottom parts

**Comment by Username1-a** [comment] 2024-08-14 21:24
@tomxposed 
Regarding video thumbnails in InnerTune, I think them just being rectangular 16:9 like in previous version makes sense since this is the original video thimbnails from YouTube

The problem is that 
1. In previous versions rectangular thumbnails were more trimmed/cut off than in original thumbnails from YouTube (resulting in image text being cut off and stuff like that)

2. In latest version video thumbnails are now squares so they are even more cut off

Here's comparison:
![350811912-f75b3c51-5414-4f97-856a-93b05aca5659](https://github.com/user-attachments/assets/da391cc1-76a8-48a5-9710-9d7ecd6993cf)
![350811904-036ebad4-d570-4544-adf0-c9211ede45e6](https://github.com/user-attachments/assets/2e13e00e-b9db-4aa5-80ad-025b085b292c)
![Screenshot_20240815-001553_Evolution X Launcher](https://github.com/user-attachments/assets/1efbc51d-79e4-44e3-b2a6-d96f7c3cb4d1)

**Comment by Spaceshiprace** [comment] 2024-08-14 23:02
> @tomxposed Regarding video thumbnails in InnerTune, I think them just being rectangular 16:9 like in previous version makes sense since this is the original video thimbnails from YouTube
> 
> The problem is that
> 
>     1. In previous versions rectangular thumbnails were more trimmed/cut off than in original thumbnails from YouTube (resulting in image text being cut off and stuff like that)
> 
>     2. In latest version video thumbnails are now squares so they are even more cut off
> 
> 
> Here's comparison: ![350811912-f75b3c51-5414-4f97-856a-93b05aca5659](https://private-user-images.githubusercontent.com/47947180/358013691-da391cc1-76a8-48a5-9710-9d7ecd6993cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NzY0NTcsIm5iZiI6MTcyMzY3NjE1NywicGF0aCI6Ii80Nzk0NzE4MC8zNTgwMTM2OTEtZGEzOTFjYzEtNzZhOC00OGE1LTk3MTAtOWQ3ZWNkNjk5M2NmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDIyNTU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0YmZmYjE1NzY3MzEyYjlmNmQ5MGQ3ODE5YTU2MTgyYmYxNGZmODI5NTY4NjgyMTdkYzM4MGMyODg2NWQxOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P6epUn4iqEIM1E0TzJFZRKQleJViIOiic0wyNGQ4eJY) ![350811904-036ebad4-d570-4544-adf0-c9211ede45e6](https://private-user-images.githubusercontent.com/47947180/358013708-2e13e00e-b9db-4aa5-80ad-025b085b292c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NzY0NTcsIm5iZiI6MTcyMzY3NjE1NywicGF0aCI6Ii80Nzk0NzE4MC8zNTgwMTM3MDgtMmUxM2UwMGUtYjlkYi00YWE1LTgwYWQtMDI1YjA4NWIyOTJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDIyNTU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3OWIzMmVlMGI4OGI3NWE4NjRmMjc3ZmZhNDIzZDg4MjNjNTJlMmZlOTE4N2I5NTUyNTdhM2YwZDUzYjFlMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DbvdDlbqe94lTm9Cki2GfNBna9y7NDIptpE_xLMkdpU) ![Screenshot_20240815-001553_Evolution X Launcher](https://private-user-images.githubusercontent.com/47947180/358013737-1efbc51d-79e4-44e3-b2a6-d96f7c3cb4d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NzY0NTcsIm5iZiI6MTcyMzY3NjE1NywicGF0aCI6Ii80Nzk0NzE4MC8zNTgwMTM3MzctMWVmYmM1MWQtNzllNC00NGUzLWIyYTYtZDk2ZjdjM2NiNGQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDIyNTU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1ZTZkNjQ4YTIxZjAwYWZhNGRjMGVmNjAxOGUxNmU5NzZmZjMzNzI4ZmVkODU0YzZiMGEzZTRhNWI0NzA5MTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LwZ5PbFbWwhUofVQCycpGrujiTjGqeXXczH9IfcmTBk)

yeah that rectangular 16:9 it is the original thumbnail but i was thinking of a way making the thumbnails appears fully in a In square shape you know what i mean..?

**Comment by tomxposed** [comment] 2024-08-15 01:40
> > @tomxposed Regarding video thumbnails in InnerTune, I think them just being rectangular 16:9 like in previous version makes sense since this is the original video thimbnails from YouTube
> > The problem is that
> > ```
> > 1. In previous versions rectangular thumbnails were more trimmed/cut off than in original thumbnails from YouTube (resulting in image text being cut off and stuff like that)
> > 
> > 2. In latest version video thumbnails are now squares so they are even more cut off
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Here's comparison: ![350811912-f75b3c51-5414-4f97-856a-93b05aca5659](https://private-user-images.githubusercontent.com/47947180/358013691-da391cc1-76a8-48a5-9710-9d7ecd6993cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NzY0NTcsIm5iZiI6MTcyMzY3NjE1NywicGF0aCI6Ii80Nzk0NzE4MC8zNTgwMTM2OTEtZGEzOTFjYzEtNzZhOC00OGE1LTk3MTAtOWQ3ZWNkNjk5M2NmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDIyNTU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0YmZmYjE1NzY3MzEyYjlmNmQ5MGQ3ODE5YTU2MTgyYmYxNGZmODI5NTY4NjgyMTdkYzM4MGMyODg2NWQxOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P6epUn4iqEIM1E0TzJFZRKQleJViIOiic0wyNGQ4eJY) ![350811904-036ebad4-d570-4544-adf0-c9211ede45e6](https://private-user-images.githubusercontent.com/47947180/358013708-2e13e00e-b9db-4aa5-80ad-025b085b292c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NzY0NTcsIm5iZiI6MTcyMzY3NjE1NywicGF0aCI6Ii80Nzk0NzE4MC8zNTgwMTM3MDgtMmUxM2UwMGUtYjlkYi00YWE1LTgwYWQtMDI1YjA4NWIyOTJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDIyNTU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3OWIzMmVlMGI4OGI3NWE4NjRmMjc3ZmZhNDIzZDg4MjNjNTJlMmZlOTE4N2I5NTUyNTdhM2YwZDUzYjFlMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DbvdDlbqe94lTm9Cki2GfNBna9y7NDIptpE_xLMkdpU) ![Screenshot_20240815-001553_Evolution X Launcher](https://private-user-images.githubusercontent.com/47947180/358013737-1efbc51d-79e4-44e3-b2a6-d96f7c3cb4d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NzY0NTcsIm5iZiI6MTcyMzY3NjE1NywicGF0aCI6Ii80Nzk0NzE4MC8zNTgwMTM3MzctMWVmYmM1MWQtNzllNC00NGUzLWIyYTYtZDk2ZjdjM2NiNGQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDIyNTU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1ZTZkNjQ4YTIxZjAwYWZhNGRjMGVmNjAxOGUxNmU5NzZmZjMzNzI4ZmVkODU0YzZiMGEzZTRhNWI0NzA5MTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LwZ5PbFbWwhUofVQCycpGrujiTjGqeXXczH9IfcmTBk)
> 
> yeah that rectangular 16:9 it is the original thumbnail but i was thinking of a way making the thumbnails appears fully in a In square shape you know what i mean..?

Will it would look nice if we use blurred of edges like i suggested in previous comment. So that the entire thumbnail will be visible and will also be square.

**Comment by Spaceshiprace** [comment] 2024-08-15 11:43
> > > @tomxposed Regarding video thumbnails in InnerTune, I think them just being rectangular 16:9 like in previous version makes sense since this is the original video thimbnails from YouTube
> > > The problem is that
> > > ```
> > > 1. In previous versions rectangular thumbnails were more trimmed/cut off than in original thumbnails from YouTube (resulting in image text being cut off and stuff like that)
> > > 
> > > 2. In latest version video thumbnails are now squares so they are even more cut off
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Here's comparison: ![350811912-f75b3c51-5414-4f97-856a-93b05aca5659](https://private-user-images.githubusercontent.com/47947180/358013691-da391cc1-76a8-48a5-9710-9d7ecd6993cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NzY0NTcsIm5iZiI6MTcyMzY3NjE1NywicGF0aCI6Ii80Nzk0NzE4MC8zNTgwMTM2OTEtZGEzOTFjYzEtNzZhOC00OGE1LTk3MTAtOWQ3ZWNkNjk5M2NmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDIyNTU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0YmZmYjE1NzY3MzEyYjlmNmQ5MGQ3ODE5YTU2MTgyYmYxNGZmODI5NTY4NjgyMTdkYzM4MGMyODg2NWQxOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P6epUn4iqEIM1E0TzJFZRKQleJViIOiic0wyNGQ4eJY) ![350811904-036ebad4-d570-4544-adf0-c9211ede45e6](https://private-user-images.githubusercontent.com/47947180/358013708-2e13e00e-b9db-4aa5-80ad-025b085b292c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NzY0NTcsIm5iZiI6MTcyMzY3NjE1NywicGF0aCI6Ii80Nzk0NzE4MC8zNTgwMTM3MDgtMmUxM2UwMGUtYjlkYi00YWE1LTgwYWQtMDI1YjA4NWIyOTJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDIyNTU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3OWIzMmVlMGI4OGI3NWE4NjRmMjc3ZmZhNDIzZDg4MjNjNTJlMmZlOTE4N2I5NTUyNTdhM2YwZDUzYjFlMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DbvdDlbqe94lTm9Cki2GfNBna9y7NDIptpE_xLMkdpU) ![Screenshot_20240815-001553_Evolution X Launcher](https://private-user-images.githubusercontent.com/47947180/358013737-1efbc51d-79e4-44e3-b2a6-d96f7c3cb4d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NzY0NTcsIm5iZiI6MTcyMzY3NjE1NywicGF0aCI6Ii80Nzk0NzE4MC8zNTgwMTM3MzctMWVmYmM1MWQtNzllNC00NGUzLWIyYTYtZDk2ZjdjM2NiNGQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDIyNTU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1ZTZkNjQ4YTIxZjAwYWZhNGRjMGVmNjAxOGUxNmU5NzZmZjMzNzI4ZmVkODU0YzZiMGEzZTRhNWI0NzA5MTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LwZ5PbFbWwhUofVQCycpGrujiTjGqeXXczH9IfcmTBk)
> > 
> > 
> > yeah that rectangular 16:9 it is the original thumbnail but i was thinking of a way making the thumbnails appears fully in a In square shape you know what i mean..?
> 
> Will it would look nice if we use blurred of edges like i suggested in previous comment. So that the entire thumbnail will be visible and will also be square.

yeah i agree, the only thing is that the edges would be better if they're just pure black instead of blurred edges i wish you understand what i talking about..
