### ISSUE TITLE
cover for playlist disappears

### ISSUE THREAD

**Issue by Spaceshiprace** [Malopieds/InnerTune#73] opened 2024-04-19 14:40 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

created a playlist, added songs to it, then a little bit while, the cover for that playlist disappears 

### Expected behavior

the playlist should have a cover when u add songs to it

### Actual behavior

no cover instead

### Screenshots/Screen recordings

![Screenshot_2024-04-19-14-22-49-525_com zionhuang music_1](https://github.com/Malopieds/InnerTune/assets/156727749/7fdea2e4-535c-422c-8cc1-4bab020187d1)
 also the position for the playlist title changed :
![Screenshot_2024-04-19-14-22-53-776_com zionhuang music_1_1](https://github.com/Malopieds/InnerTune/assets/156727749/17347a64-f308-4ec0-975b-c91b43df09f1)

### Logs

idk

### InnerTune version

0.5.7

### Android version

Android 12

**Comment by Malopieds** [comment] 2024-04-20 14:32
Hi, I cannot reproduce it. What have you done other than just wait ?

**Comment by Spaceshiprace** [comment] 2024-04-23 20:10
so it takes time from me to realize that it happened everytime i remove a song from the playlist, maybe that why..

**Comment by Malopieds** [comment] 2024-06-25 07:47
Hi, I fixed some things in the playlist section that might have resolved this, is this still occurring with the latest debug version?

**Comment by Spaceshiprace** [comment] 2024-06-25 11:17
I'm using 0.5.7-rc-2 now, and it seems like its resolved now

**Comment by Malopieds** [comment] 2024-06-27 09:02
> I'm using 0.5.7-rc-2 now, and it seems like its resolved now

Ok, I'll close this issue, reopen it if you have this issue again !

**Closed as completed by Malopieds** 2024-06-27 09:02 UTC
Labels: bug

**Comment by mostafaalagamy** [comment] 2024-06-27 12:35
> issue again

Issue back again 
 
* The issue occurs when a song is removed from the list.

**Comment by Malopieds** [comment] 2024-06-27 13:33
> The issue occurs when a song is removed from the list.

How do you reproduce it? Simply removing it works.

**Comment by mostafaalagamy** [comment] 2024-06-27 13:57
> > The issue occurs when a song is removed from the list.
> 
> How do you reproduce it? Simply removing it works.

https://github.com/Malopieds/InnerTune/assets/80542861/14e37f02-f284-4563-801c-b2ba886dc242

**Comment by Malopieds** [comment] 2024-06-27 15:38
Ok, now should be fix for good I hope.

**Comment by Spaceshiprace** [comment] 2024-06-27 16:06
> Ok, now should be fix for good I hope.

u mean that this would be fixed in the next release, Right?

**Comment by Malopieds** [comment] 2024-06-27 16:07
> u mean that this would be fixed in the next release, Right?

Yes but you can try it out since last debug release

**Comment by mostafaalagamy** [comment] 2024-06-27 16:08
> Ok, now should be fix for good I hope

![Screenshot_2024-06-27-19-06-26-024_com.miui.bugreport.jpg](https://github.com/Malopieds/InnerTune/assets/80542861/06554b4e-bd38-4623-8a1f-f538ca4185f9)

When adding songs to Playlist, the app crash

**Comment by Malopieds** [comment] 2024-06-27 16:10
> When adding songs to Playlist, the app crash

It should have been fixed it 2 commits ago, did you use the last debug version? What were the steps to reproduce it?

**Comment by mostafaalagamy** [comment] 2024-06-27 16:16
> > When adding songs to Playlist, the app crash
> 
> It should have been fixed it 2 commits ago, did you use the last debug version? What were the steps to reproduce it?

Latest debug v 

https://github.com/Malopieds/InnerTune/assets/80542861/043d601f-0bf7-4b2c-be30-1fa8df4258a8

**Comment by Spaceshiprace** [comment] 2024-06-27 19:19
> > u mean that this would be fixed in the next release, Right?
> 
> Yes but you can try it out since last debug release

No, I will wait for the release since that debug version is lagging for me

**Comment by Malopieds** [comment] 2024-06-27 20:02
> When adding songs to Playlist, the app crash

Also fixed in last commit

**Comment by mostafaalagamy** [comment] 2024-06-28 00:38
> > When adding songs to Playlist, the app crash
> 
> Also fixed in last commit

Solved , done
