### ISSUE TITLE
Date and time and other

### ISSUE THREAD

**Issue by Mrunknow3** [Malopieds/InnerTune#326] opened 2024-08-17 04:43 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1 go on app
2 go to download
3 click date and time to change name
4 nothing change

### Expected behavior

This should be change

### Actual behavior

Songs should change 

### Screenshots/Screen recordings

Nothing

### Logs

Nothing

### InnerTune version

0.5.9

### Android version

Android 13

### Additional information

Nothing

**Comment by Malopieds** [comment] 2024-08-17 06:36
Duplicate of #142

**Closed as completed** 2024-08-17 06:36 UTC
Labels: bug
