### ISSUE TITLE
edit/sync with ytm

### ISSUE THREAD

**Issue by Nilsu11** [Malopieds/InnerTune#215] opened 2024-07-12 13:38 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Shortly said, I want the innertune app to be able edit, create YouTube music playlists and have the liked songs synced with YouTube's liked songs. This should be coupled with a switch in settings and the signing option in settings

### Why do you want this feature?

This can sync music playlists between devices and enables a better transition between devices. It also supports better implementation for YouTube's personalization features (see other enhancements).

### Additional information

Please ask for further details

**Comment by Malopieds** [comment] 2024-07-12 18:33
Duplicate of #15 (won't be worked on by me as of now, any PR are welcomed though)

**Closed as completed by Malopieds** 2024-07-12 18:33 UTC
Labels: enhancement
