### ISSUE TITLE
Option to switch to old player colors

### ISSUE THREAD

**Issue by MedwardR** [Malopieds/InnerTune#244] opened 2024-07-20 17:21 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [x] The title of this issue accurately describes the feature request.

### Feature description

It would be cool to have an option to switch to old player colors.

### Why do you want this feature?

New colors are too bright to look good with most album covers (the UI stands out more than the actual content). This is just personal prefrence though, and the bolder colors do look pretty cool with some songs.

### Additional information

![Screenshot_20240720-131318_InnerTune](https://github.com/user-attachments/assets/4ab0034f-f02d-4222-ad3c-33cbb403e665)
![Screenshot_20240720-123658_InnerTune](https://github.com/user-attachments/assets/64f68b77-5d7b-42a4-9468-016456b93196)

PS: thanks for continuing the development of this app!

PPS: the squiggly slider looks sick

**Comment by BluePixel4k** [comment] 2024-08-10 06:47
I prefer the old colors with the new UI too.
But I think the issue is a duplicate of https://github.com/Malopieds/InnerTune/issues/218

**Closed as completed** 2024-08-13 08:27 UTC
Labels: enhancement
