### ISSUE TITLE
Unknown error 

### ISSUE THREAD

**Issue by Sunilr001** [Malopieds/InnerTune#444] opened 2024-12-24 14:20 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Songs do not play after 30 seconds; it shows an unknown error.

### Expected behavior

It should be play.

### Actual behavior

It should be play.

### Logs

Show unknown error after 30 seconds 

### InnerTune version

0.5.12

### Android version

Android 14

**Comment by Malopieds** [comment] 2024-12-24 16:58
Duplicate of #433

**Closed as completed by Malopieds** 2024-12-24 16:58 UTC
Labels: bug
