### ISSUE TITLE
The song lyrics don't respond

### ISSUE THREAD

**Issue by mostafaalagamy** [Malopieds/InnerTune#88] opened 2024-05-02 16:45 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

When searching for song lyrics, the app crashes

### Expected behavior

.

### Actual behavior

.

### Screenshots/Screen recordings

https://github.com/Malopieds/InnerTune/assets/80542861/6de73020-3092-4be9-89e1-c950f4424b26

### Logs

![Screenshot_2024-05-02-19-33-26-768_com miui bugreport](https://github.com/Malopieds/InnerTune/assets/80542861/d6725c3f-62b5-4d75-894f-37b23eb3a998)
![Screenshot_2024-05-02-19-30-18-580_com miui bugreport](https://github.com/Malopieds/InnerTune/assets/80542861/7b8053d1-45a6-4bd4-a21e-1e55b4e90318)
![Screenshot_2024-05-02-19-30-05-332_com miui bugreport](https://github.com/Malopieds/InnerTune/assets/80542861/2b45e162-e555-4ad4-b8d5-652d95ad1163)

### InnerTune version

debug version

### Android version

13

**Comment by SiddhantRakh** [comment] 2024-05-02 21:53
This is happening on latest stable release as well. The same issue was fixed in the release in which lrclib was added as an alternative lyrics source. But now I think we are back to square one. 😔

**Comment by SiddhantRakh** [comment] 2024-05-05 23:36
@mostafaalagamy Have you found any solution to this problem?

**Comment by SiddhantRakh** [comment] 2024-05-06 00:56
Hey, I just reinstalled the app completely and the lyrics are working fine again. 😊
Maybe the lyrics source was down or something specific that is causing this issue.

**Comment by SiddhantRakh** [comment] 2024-05-06 02:14
Well only the lyrics from Kuguo are working as of now. Lrclib lyrics don't show on refetching. We really are back to square one in terms of lyrics functionality. 😔

**Comment by mostafaalagamy** [comment] 2024-05-07 13:11
> @mostafaalagamy Have you found any solution to this problem? 

I don't have access to my device at the moment. We'll wait for Malopieds response.

**Comment by mostafaalagamy** [comment] 2024-05-07 13:14
> Well only the lyrics from Kuguo are working as of now. Lrclib lyrics don't show on refetching. We really are back to square one in terms of lyrics functionality. 😔

The problem is specific to lrclib, so the app crashes when searching, but Kuguo is working.

**Comment by SiddhantRakh** [comment] 2024-05-08 04:51
> > @mostafaalagamy Have you found any solution to this problem?
> 
> I don't have access to my device at the moment. We'll wait for Malopieds response.

Why is Malopeids so slow to respond nowadays? I know people have more important things in life but I am just asking whether he has stated about this anywhere on GitHub.

**Comment by mostafaalagamy** [comment] 2024-05-13 09:20
> > > @mostafaalagamy Have you found any solution to this problem?
> > 
> > I don't have access to my device at the moment. We'll wait for Malopieds response.
> 
> Why is Malopeids so slow to respond nowadays? I know people have more important things in life but I am just asking whether he has stated about this anywhere on GitHub.

Idk , but the issue of crashing in my specific version has been temporarily fixed by removing lrclib.

**Comment by SiddhantRakh** [comment] 2024-05-13 09:31
> Idk , but the issue of crashing in my specific version has been temporarily fixed by removing lrclib.

I would love to use your version (Metrolist), but the three dots (menu) icon looks a bit ugly to me.
I can't rely on Kuguo, as it lacks lyrics for most of the songs I listen to. Lrclib was the best addition to InnerTune, but this recent bug has ruined my lyrics experience (again).
I hope Malopeids looks into this as soon as possible.

**Comment by mostafaalagamy** [comment] 2024-05-13 09:36
> I would love to use your version (Metrolist), but the three dots (menu) icon looks a bit ugly to me.

It's possible to change it in the next release.

**Comment by SiddhantRakh** [comment] 2024-05-13 09:39
> > I would love to use your version (Metrolist), but the three dots (menu) icon looks a bit ugly to me.
> 
> It's possible to change it in the next release.

It would be great if it gets changed because except this I really like the other improved icons.

**Comment by mostafaalagamy** [comment] 2024-05-13 09:39
> I can't rely on Kuguo, as it lacks lyrics for most of the songs I listen to. Lrclib was the best addition to InnerTune, but this recent bug has ruined my lyrics experience (again).\nI hope Malopeids looks into this as soon as possible.

We are waiting for Malopieds, and I will also work on fixing it in the next release.

**Comment by SiddhantRakh** [comment] 2024-05-13 10:00
> > I can't rely on Kuguo, as it lacks lyrics for most of the songs I listen to. Lrclib was the best addition to InnerTune, but this recent bug has ruined my lyrics experience (again).\nI hope Malopeids looks into this as soon as possible.
> 
> We are waiting for Malopieds, and I will also work on fixing it in the next release.

Thanks. Please fix it if you can as according to me lyrics is the only major bug left in InnerTune as of my usage to the point that I have stopped using InnerTune. 

Maybe you can take a look at ViTune. It also uses Lrclib as lyrics provider and as a result has lyrics to a wider range of songs. But still I like InnerTune's lyrics UI.

**Comment by Malopieds** [comment] 2024-05-17 13:10
Hi all, I didn't had (and still don't have...) a lot of free time lately. I will try to look into this as soon as possible.

**Comment by Malopieds** [comment] 2024-05-17 13:46
This should fix (I hope for good) the lyrics part.

**Comment by SiddhantRakh** [comment] 2024-05-17 13:52
> Hi all, I didn't had (and still don't have...) a lot of free time lately. I will try to look into this as soon as possible.

No problem. I was just annoyed by it lately. Thanks a lot for taking the time to commit, even though you're busy.

**Comment by SiddhantRakh** [comment] 2024-05-17 14:24
> This should fix (I hope for good) the lyrics part.

I can confirm that the issue has been resolved by the commit.

**Closed as completed** 2024-05-17 20:26 UTC
Labels: bug
