### ISSUE TITLE
Song still not playing after the latest update 

### ISSUE THREAD

**Issue by watashinosoulsociety** [Malopieds/InnerTune#417] opened 2024-11-28 18:13 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

I just looked up songs and tried to play them but they didn't work for some reason and kept on saying unknown error

### Expected behavior

The song should play 

### Actual behavior

Says unknown error

### Screenshots/Screen recordings

![Uploading Screenshot_2024-11-28-23-43-42-20_56635af9b6ad4512d4187a5a49185a25.jpg…]()

### Logs

I do not know 

### InnerTune version

0.5.11

### Android version

Android 13

### Additional information

Nil

**Comment by Malopieds** [comment] 2024-11-28 18:27
Duplicate of #410

**Closed as completed** 2024-11-28 18:28 UTC
Labels: bug
