### ISSUE TITLE
can't play an downloaded offline songs while no internet connection

### ISSUE THREAD

**Issue by pindeck** [Malopieds/InnerTune#149] opened 2024-06-29 11:20 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

play an downloaded songs on "offline" while having no internet connection

### Expected behavior

it just plays

### Actual behavior

it wouldn't and can only play songs on the history

### Screenshots/Screen recordings

https://github.com/Malopieds/InnerTune/assets/136303386/ac4bf1be-818c-44fd-8039-88fed3e5187a

### Logs

if it's unclear ill add it

### InnerTune version

0.5.7-rc2 and 0.5.7-rc1

### Android version

Android 14

### Additional information

and sometimes it would crash when no connections too

**Comment by Malopieds** [comment] 2024-06-30 07:40
Duplicate of #41

**Closed as completed by Malopieds** 2024-06-30 07:40 UTC
Labels: bug
