### ISSUE TITLE
"Add to library" is missing on whole album

### ISSUE THREAD

**Issue by sojusnik** [Malopieds/InnerTune#57] opened 2024-04-07 21:26 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

While you can add a song to the library, it's not possible with a whole album, because the corresponding button is missing.

### Expected behavior

There should be a button in albums to "add to library".

### Actual behavior

"Add to library" button is missing on whole album.

### Logs

no logs needed

### InnerTune version

v0.5.6

### Android version

Android 13

**Comment by mostafaalagamy** [comment] 2024-04-07 21:31
> ### Checklist
> 
> - [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
> - [X] I've checked that there is no open or closed issue about this bug.
> - [X] This issue contains only one bug.
> - [X] The title of this issue accurately describes the bug.
> 
> ### Steps to reproduce the bug
> 
> While you can add a song to the library, it's not possible with a whole album, because the corresponding button is missing.
> 
> ### Expected behavior
> 
> There should be a button in albums to "add to library".
> 
> ### Actual behavior
> 
> "Add to library" button is missing on whole album.
> 
> ### Screenshots/Screen recordings
> 
> _No response_
> 
> ### Logs
> 
> no logs needed
> 
> ### InnerTune version
> 
> v0.5.6
> 
> ### Android version
> 
> Android 13
> 
> ### Additional information
> 
> _No response_

like button does the same job

**Comment by sojusnik** [comment] 2024-04-07 21:39
> > ### Checklist
> > 
> > * [x]  I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
> > * [x]  I've checked that there is no open or closed issue about this bug.
> > * [x]  This issue contains only one bug.
> > * [x]  The title of this issue accurately describes the bug.
> > 
> > ### Steps to reproduce the bug
> > While you can add a song to the library, it's not possible with a whole album, because the corresponding button is missing.
> > ### Expected behavior
> > There should be a button in albums to "add to library".
> > ### Actual behavior
> > "Add to library" button is missing on whole album.
> > ### Screenshots/Screen recordings
> > _No response_
> > ### Logs
> > no logs needed
> > ### InnerTune version
> > v0.5.6
> > ### Android version
> > Android 13
> > ### Additional information
> > _No response_
> 
> like button does the same job

no, see https://github.com/Malopieds/InnerTune/issues/58

**Comment by mostafaalagamy** [comment] 2024-04-07 21:41
The 'remove from library' option must be added to all sections of the library.

![Screenshot_20240407_233531.jpg](https://github.com/Malopieds/InnerTune/assets/80542861/1e4c0f7d-1b06-4951-b07f-db53fe9d36de)

**Comment by mostafaalagamy** [comment] 2024-04-07 21:45
> > > ### Checklist
> > > 
> > > * [x]  I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
> > > * [x]  I've checked that there is no open or closed issue about this bug.
> > > * [x]  This issue contains only one bug.
> > > * [x]  The title of this issue accurately describes the bug.
> > > 
> > > ### Steps to reproduce the bug
> > > While you can add a song to the library, it's not possible with a whole album, because the corresponding button is missing.
> > > ### Expected behavior
> > > There should be a button in albums to "add to library".
> > > ### Actual behavior
> > > "Add to library" button is missing on whole album.
> > > ### Screenshots/Screen recordings
> > > _No response_
> > > ### Logs
> > > no logs needed
> > > ### InnerTune version
> > > v0.5.6
> > > ### Android version
> > > Android 13
> > > ### Additional information
> > > _No response_
> > 
> > like button does the same job
> 
> no, see https://github.com/Malopieds/InnerTune/issues/58

Oh yes, Some albums and artists don't appear in library.

**Comment by mostafaalagamy** [comment] 2024-04-07 22:27
> Oh yes, Some albums and artists don't appear in library.

https://github.com/Malopieds/InnerTune/assets/80542861/395b11b9-ae11-4055-a650-8fdbf65f62f9

**Comment by sojusnik** [comment] 2024-04-08 06:34
> Oh yes, Some albums and artists don't appear in library.

Can confirm that here as well with the missing artist.

The favorite artist will only appear, if you add a song from an album of a favorite artist, provided that you open the album after marking one song of this album as favorite. So a favorite artist will only be shown in the library, if you mark one or more songs from him/her as favorite too, not just the artist, which IMHO is a bug.

**Comment by Malopieds** [comment] 2024-04-08 06:51
Hi all, I know that issue. But for me library in the database is too messy. I mean for me, only artistes/albums that you specifically add to your library/like should be added to to your library, not the artists from all the liked songs. But maybe I'm just not using same as you. What do you think?

**Comment by sojusnik** [comment] 2024-04-08 07:26
> I mean for me, only artistes/albums that you specifically add to your library/like should be added to to your library, not the artists from all the liked songs.

Seems that my description wasn't clear about the favorite artist missing in the library, so I updated it. What I'm describing is actually a bug, not a feature I would like to see.

**Comment by Malopieds** [comment] 2024-04-08 07:58
> Seems that my description wasn't clear about the favorite artist missing in the library, so I updated it. What I'm describing is actually a bug, not a feature I would like to see.

No I understood it well. I'm just saying that later on, it will be 'like' everywhere that would be library, it's simpler and when you click on like it appears on the library (the album, not ALL the songs). Or maybe I'll let the like to only the songs and let add to library button instead of like for artists/albums. I still don't know but I need some feedback.

**Comment by mostafaalagamy** [comment] 2024-04-08 08:28
> > Seems that my description wasn't clear about the favorite artist missing in the library, so I updated it. What I'm describing is actually a bug, not a feature I would like to see.
> 
> No I understood it well. I'm just saying that later on, it will be 'like' everywhere that would be library, it's simpler and when you click on like it appears on the library (the album, not ALL the songs). Or maybe I'll let the like to only the songs and let add to library button instead of like for artists/albums. I still don't know but I need some feedback.

You use the same working method as YT Music library, don't you! However, here we will face the same issue that the artist or album doesn't appear in the main library. If the issue is resolved, there will be a missing sorting feature to display recently added items at the top of the list ,I don't prefer the way YT Music handles this matter, but you can also add an 'add to library' button as a solution to display in all sections of the library.

**Comment by Malopieds** [comment] 2024-04-08 12:57
To clarify everything. Right now the system works as: if a song is liked, it adds the albums and the artist(s) to the library. This is similar to Youtube Music system. I don't like this system. What I was thinking as a workaround is the following:
- The songs liked appears both in the "liked" playlist and in the songs Chips of the library. 
- The artists and albums, to appear in their respective chips must be "added to the library" or "Liked" on the respective page. I don't know if the icon for that should be a heart (same as liked songs) or the current add to library icon.
That way, you only have strictly the artists/albums that you added to you library and not simply artists that are linked to the liked song.

This way this "issue" would be resolved (same for #58 )
What do you all think about this idea ?

**Comment by mostafaalagamy** [comment] 2024-04-08 14:01
> To clarify everything. Right now the system works as: if a song is liked, it adds the albums and the artist(s) to the library. This is similar to Youtube Music system. I don't like this system. What I was thinking as a workaround is the following:
> - The songs liked appears both in the "liked" playlist and in the songs Chips of the library. 
> - The artists and albums, to appear in their respective chips must be "added to the library" or "Liked" on the respective page. I don't know if the icon for that should be a heart (same as liked songs) or the current add to library icon.
> That way, you only have strictly the artists/albums that you added to you library and not simply artists that are linked to the liked song.
> 
> This way this "issue" would be resolved (same for #58 )
> What do you all think about this idea ?

Good idea

**Comment by mostafaalagamy** [comment] 2024-04-08 14:06
> same as liked songs

I prefer like icon

**Comment by SiddhantRakh** [comment] 2024-04-08 19:07
Integrate add to library into like function and remove the add to library button. This will simplify things as adding to library and liking a thing has the same purpose to save it for future so I think like is the way to go as it is more popular and user-friendly. Also we removed the add to library button from the player UI in the recent debug build so this change will be in line with it.

**Closed as completed** 2024-04-08 19:57 UTC
Labels: bug
