### ISSUE TITLE
After pressing lyrics button to turn them on or off song starts from the start

### ISSUE THREAD

**Issue by PsychoAsylum** [Malopieds/InnerTune#6] opened 2024-03-22 21:33 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

It happens only sometimes but i was able to reproduce it
1. Start playing a song with lyrica on
2. Close app fully
3. Open again and start playing a song and now turn off lyrics

### Expected behavior

It should show lyrics if available

### Actual behavior

It shows lyrics as intended and  starts playing song from the start

### Screenshots/Screen recordings

![Media_240322_222213](https://github.com/Malopieds/InnerTune/assets/72300906/2d25798b-db31-4b42-81ad-e0091ab6801a)

### Logs

Don't have

### InnerTune version

0.5.5 and 0.5.5 with " Fixing mini player problems"

### Android version

Android 10

**Comment by Malopieds** [comment] 2024-03-24 08:52
Was this bug fixed with the [same commit](https://github.com/Malopieds/InnerTune/commit/7045950665e54eef6cb8fe2ae3abe0d22db9b81b) ?

**Comment by PsychoAsylum** [comment] 2024-03-25 17:00
Unfortunately not.
It happens mostly after launching app.
But even when its cleared from cache and still playing in the background  then after getting back to the player and pressing lyrics then song starts from the start

**Comment by Malopieds** [comment] 2024-03-25 17:49
when you say
> close app fully

You mean stop the music too ? I still cannot reproduce with those steps.
Does it happens with the [original app](https://github.com/z-huang/InnerTune)

**Comment by mostafaalagamy** [comment] 2024-03-25 18:05
> ### Checklist
> 
> - [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
> - [X] I've checked that there is no open or closed issue about this bug.
> - [X] This issue contains only one bug.
> - [X] The title of this issue accurately describes the bug.
> 
> ### Steps to reproduce the bug
> 
> It happens only sometimes but i was able to reproduce it
> 1. Start playing a song with lyrica on
> 2. Close app fully
> 3. Open again and start playing a song and now turn off lyrics
> 
> ### Expected behavior
> 
> It should show lyrics if available
> 
> ### Actual behavior
> 
> It shows lyrics as intended and  starts playing song from the start
> 
> ### Screenshots/Screen recordings
> 
> ![Media_240322_222213](https://github.com/Malopieds/InnerTune/assets/72300906/2d25798b-db31-4b42-81ad-e0091ab6801a)
> 
> 
> ### Logs
> 
> Don't have
> 
> ### InnerTune version
> 
> 0.5.5 and 0.5.5 with " Fixing mini player problems"
> 
> ### Android version
> 
> Android 10
> 
> ### Additional information
> 
> _No response_

 You should try this version 

[]()https://github.com/Malopieds/InnerTune/actions/runs/8402086684/artifacts/1352445328

**Comment by PsychoAsylum** [comment] 2024-03-25 19:59
What i mean is that after i launch innertune it happens and after i close app but music is still playing and i launch it back up i happens again 
![Media_240325_205237](https://github.com/Malopieds/InnerTune/assets/72300906/086a00d9-99bd-44b7-bd93-f54c038b893a)

**Comment by PsychoAsylum** [comment] 2024-03-25 20:01
> > ### Checklist
> > 
> > * [x]  I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
> > * [x]  I've checked that there is no open or closed issue about this bug.
> > * [x]  This issue contains only one bug.
> > * [x]  The title of this issue accurately describes the bug.
> > 
> > ### Steps to reproduce the bug
> > It happens only sometimes but i was able to reproduce it
> > 
> > 1. Start playing a song with lyrica on
> > 2. Close app fully
> > 3. Open again and start playing a song and now turn off lyrics
> > 
> > ### Expected behavior
> > It should show lyrics if available
> > ### Actual behavior
> > It shows lyrics as intended and  starts playing song from the start
> > ### Screenshots/Screen recordings
> > ![Media_240322_222213](https://private-user-images.githubusercontent.com/72300906/316172396-2d25798b-db31-4b42-81ad-e0091ab6801a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzOTY0MDYsIm5iZiI6MTcxMTM5NjEwNiwicGF0aCI6Ii83MjMwMDkwNi8zMTYxNzIzOTYtMmQyNTc5OGItZGIzMS00YjQyLTgxYWQtZTAwOTFhYjY4MDFhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDE5NDgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmYTkyMjIxYWI5YzBiNDRmYmNjNDJjNjZkYzhiNTRkZDJkNDUxM2JlMTk3NzI4NDE2ZjI4ZjQyZDc5N2VkZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i428-34SgkKI0j0GJ-yisP3wnHXnflhIjVEjoX3QO6c)
> >       
> >         [
> >           
> >         
> >             ![Media_240322_222213](https://private-user-images.githubusercontent.com/72300906/316172396-2d25798b-db31-4b42-81ad-e0091ab6801a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzOTY0MDYsIm5iZiI6MTcxMTM5NjEwNiwicGF0aCI6Ii83MjMwMDkwNi8zMTYxNzIzOTYtMmQyNTc5OGItZGIzMS00YjQyLTgxYWQtZTAwOTFhYjY4MDFhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDE5NDgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmYTkyMjIxYWI5YzBiNDRmYmNjNDJjNjZkYzhiNTRkZDJkNDUxM2JlMTk3NzI4NDE2ZjI4ZjQyZDc5N2VkZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i428-34SgkKI0j0GJ-yisP3wnHXnflhIjVEjoX3QO6c)
> >           ](https://private-user-images.githubusercontent.com/72300906/316172396-2d25798b-db31-4b42-81ad-e0091ab6801a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzOTY0MDYsIm5iZiI6MTcxMTM5NjEwNiwicGF0aCI6Ii83MjMwMDkwNi8zMTYxNzIzOTYtMmQyNTc5OGItZGIzMS00YjQyLTgxYWQtZTAwOTFhYjY4MDFhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDE5NDgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmYTkyMjIxYWI5YzBiNDRmYmNjNDJjNjZkYzhiNTRkZDJkNDUxM2JlMTk3NzI4NDE2ZjI4ZjQyZDc5N2VkZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i428-34SgkKI0j0GJ-yisP3wnHXnflhIjVEjoX3QO6c)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://private-user-images.githubusercontent.com/72300906/316172396-2d25798b-db31-4b42-81ad-e0091ab6801a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzOTY0MDYsIm5iZiI6MTcxMTM5NjEwNiwicGF0aCI6Ii83MjMwMDkwNi8zMTYxNzIzOTYtMmQyNTc5OGItZGIzMS00YjQyLTgxYWQtZTAwOTFhYjY4MDFhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDE5NDgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmYTkyMjIxYWI5YzBiNDRmYmNjNDJjNjZkYzhiNTRkZDJkNDUxM2JlMTk3NzI4NDE2ZjI4ZjQyZDc5N2VkZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i428-34SgkKI0j0GJ-yisP3wnHXnflhIjVEjoX3QO6c)
> >         
> >       
> > ### Logs
> > Don't have
> > ### InnerTune version
> > 0.5.5 and 0.5.5 with " Fixing mini player problems"
> > ### Android version
> > Android 10
> > ### Additional information
> > _No response_
> 
> You should try this version
> 
> https://github.com/Malopieds/InnerTune/actions/runs/8402086684/artifacts/1352445328

Unfortunately it still happens

**Comment by mostafaalagamy** [comment] 2024-03-25 20:04
> What i mean is that after i launch innertune it heppens and after i close app but music is still playing and i launch it back up i heppens again 
> ![Media_240325_205237](https://github.com/Malopieds/InnerTune/assets/72300906/086a00d9-99bd-44b7-bd93-f54c038b893a)
> 

It has been resolved. Wait for the stable version

**Comment by Malopieds** [comment] 2024-03-25 22:42
> It has been resolved. Wait for the stable version

Actually, I think that the implementation of swiping (which is the root of all the issues here) is not yet good enough...
This means that either we lose the ability to swipe on the thumbnail to gain some stability or we sacrifice the stability.
I'm trying a lot to get this to work but I don't think it's really doable right now.

**Comment by mostafaalagamy** [comment] 2024-03-25 22:56
> > It has been resolved. Wait for the stable version
> 
> Actually, I think that the implementation of swiping (which is the root of all the issues here) is not yet good enough...
> This means that either we lose the ability to swipe on the thumbnail to gain some stability or we sacrifice the stability.
> I'm trying a lot to get this to work but I don't think it's really doable right now.

As I mentioned earlier, I've tried extensively to fix the swiping issue, but it hasn't been successful. I believe it's necessary to write the code from zero to solve this problem. Therefore, it's better to sacrifice it for now.

**Comment by Malopieds** [comment] 2024-03-28 20:13
Hi, [this commit](https://github.com/Malopieds/InnerTune/commit/e9f75f80645ca4314e0ebdd867dd0dc424146b13) should fix the issue (I reverted from the original repo)

**Comment by Malopieds** [comment] 2024-04-06 17:41
Closing this since it's now fixed in the latest release.

**Closed as completed by Malopieds** 2024-04-06 17:41 UTC
Labels: bug
