### ISSUE TITLE
Add Widget

### ISSUE THREAD

**Issue by ZTechDev06** [Malopieds/InnerTune#297] opened 2024-08-11 15:23 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Add widget play skip  ( YouTube music)

### Why do you want this feature?

Skip musicale play 

### Additional information

Add widget play pause ( YouTube music)

**Comment by Malopieds** [comment] 2024-08-11 15:24
Duplicate of #179

**Closed as completed by Malopieds** 2024-08-11 15:24 UTC
Labels: enhancement
