### ISSUE TITLE
Android shortcuts not working 

### ISSUE THREAD

**Issue by Lorestan00** [Malopieds/InnerTune#271] opened 2024-07-29 14:48 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

If you long press on the app icon
Shortcuts appear such as songs and playlist (see screenshot)

### Expected behavior

Clicking these shortcuts should take you through to the relevant section

### Actual behavior

Instead clicking any of them opens up the home tab

### Screenshots/Screen recordings

![Screenshot_2024-07-29-15-45-37-71_b783bf344239542886fee7b48fa4b892](https://github.com/user-attachments/assets/076fb462-2dd2-4060-a0a3-7878c486ebe6)

### Logs

-

### InnerTune version

0.5.8

### Android version

14

**Comment by Malopieds** [comment] 2024-07-29 17:29
Duplicate of #71

**Closed as completed** 2024-07-29 17:30 UTC
Labels: bug
