### ISSUE TITLE
no stream available

### ISSUE THREAD

**Issue by xlipse7** [Malopieds/InnerTune#206] opened 2024-07-11 19:18 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

play the morad-contento song or bzrp sesion-natael cano

### Expected behavior

should the song get played

### Actual behavior

doest got playd(on previus build the morad song get played without issues)

### Logs

aa
![Screenshot_20240711_210928_InnerTune](https://github.com/user-attachments/assets/2a236ec0-4f29-4910-ac28-6060e3efb07b)
![Screenshot_20240711_210944_InnerTune](https://github.com/user-attachments/assets/f6906a90-82d4-4d00-b7e4-37c5aeae84d3)
![Screenshot_20240711_211002_InnerTune](https://github.com/user-attachments/assets/517df8d4-1528-4ed2-b561-00b810f8d2a0)
![Screenshot_20240711_205717_InnerTune](https://github.com/user-attachments/assets/fb81d5e6-6313-43f9-b172-de9115a2967c)

### InnerTune version

latest

### Android version

Android 14

**Comment by Malopieds** [comment] 2024-07-11 19:30
Duplicate of #178

**Closed as completed** 2024-07-11 19:30 UTC
Labels: bug

**Comment by Hikari2w2** [comment] 2024-07-11 20:18
I got the same problem, i was able to play my songs again by resetting my app from scratch, but when importing backup again, a lot of songs won't play anymore.

**Comment by Richard38907** [comment] 2024-08-09 10:04
![Screenshot_20240809-115946_Kiwi Browser.png](https://github.com/user-attachments/assets/02677c67-170b-49bf-af8c-3bcdb51327dd)

Why are you in itag 774 with ~300 kbps?
All the songs I try to play are on itag 251 with ~150 kbps (which is of lower sound quality). Did youtube limit the quality of its songs?

![Screenshot_20240809-120707_InnerTune.png](https://github.com/user-attachments/assets/c282a817-0038-40ab-895f-cf564cc02297)



The same song as yours
