### ISSUE TITLE
more playlist customization

### ISSUE THREAD

**Issue by zettaexa** [Malopieds/InnerTune#327] opened 2024-08-17 06:42 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

a button that brings up a menu to change the title of a playlist, choose a playlist cover, and to add a description

### Why do you want this feature?

would give an advantage over the regular yt music app as you can only add a title and description

**Comment by Malopieds** [comment] 2024-08-17 08:20
Duplicate of #224

**Closed as completed** 2024-08-17 08:20 UTC
Labels: enhancement
