### ISSUE TITLE
Latest version completely messed up my liked songs order

### ISSUE THREAD

**Issue by ThatOneCalculator** [Malopieds/InnerTune#314] opened 2024-08-14 19:24 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Update
2. Go to liked songs

### Expected behavior

My liked songs order stays the same

### Actual behavior

The "date added" is completely messed up, everything is out of order

### Logs

N/A

### InnerTune version

0.5.9

### Android version

14

**Comment by ThatOneUnoriginal** [comment] 2024-08-16 04:26
Tried myself by liking a song and then checking where it appeared on the Liked playlisted listed by Date Added. The song should appear at the absolute top or absolute bottom since it was the most recently liked song yet it appeared in the middle of the list. Here is a video of it;

https://github.com/user-attachments/assets/f5736a86-5199-4440-bafd-f42aab304e77

**Comment by mikedizhur** [comment] 2024-08-18 19:22
Duplicate of #310 and the issue appeared in #160 (for reference)

**Closed as not planned** 2024-08-18 20:07 UTC
Labels: bug
