### ISSUE TITLE
 I would like to be able to play music stored on the device.

### ISSUE THREAD

**Issue by sf26311646** [Malopieds/InnerTune#281] opened 2024-08-01 22:51 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Enables playback of music stored on the device.
It then allows them to be added to the playlist.

### Why do you want this feature?

I go out of my way to use other apps to listen to music stored on my device, and it would be so much easier if they were integrated.

**Comment by Malopieds** [comment] 2024-08-02 10:48
Duplicate of #146

**Closed as completed by Malopieds** 2024-08-02 10:48 UTC
Labels: enhancement
