### ISSUE TITLE
more enhancement for the stats

### ISSUE THREAD

**Issue by Spaceshiprace** [Malopieds/InnerTune#84] opened 2024-04-29 22:42 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

i think it would be cool if we can see how many times we played a single song.

### Why do you want this feature?

I want to know how many time I played a certain song sometimes..

**Comment by Malopieds** [comment] 2024-05-03 09:23
Closing. Duplicate of #21.

**Closed as completed by Malopieds** 2024-05-03 09:23 UTC
Labels: enhancement
