### ISSUE TITLE
Simple Typographical Error

### ISSUE THREAD

**Issue by OnyxJet** [Malopieds/InnerTune#251] opened 2024-07-22 15:06 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Go to settings
2. Go to "About"

### Expected behavior

"my" should have been spelled "by"

### Actual behavior

No real "behavior", just a simple error.

### Screenshots/Screen recordings

![IMG_20240722_110523](https://github.com/user-attachments/assets/be9046e2-a965-4121-af27-c53b96ffd8ec)

![Screenshot_2024-07-22-10-58-52-54_56635af9b6ad4512d4187a5a49185a25](https://github.com/user-attachments/assets/b05924af-79fe-4d34-a346-af02fd5ea1a9)

### Logs

Logs aren't really necessary for a UI typo.

### InnerTune version

0.5.7

### Android version

Android 13

### Additional information

Just found this earlier. Thought I would make it known.

**Comment by Malopieds** [comment] 2024-07-22 15:14
Duplicate of #246

**Closed as completed by Malopieds** 2024-07-22 15:14 UTC
Labels: bug

**Comment by OnyxJet** [comment] 2024-07-22 15:16
Dang I searched and still missed a duplicate :/
