### ISSUE TITLE
Songs not playing.

### ISSUE THREAD

**Issue by Sunilr001** [Malopieds/InnerTune#414] opened 2024-11-28 05:00 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Play any song but songs not playing.

### Expected behavior

Play songs

### Actual behavior

Unknown error show.

### Screenshots/Screen recordings

![Screenshot_20241128_102842_InnerTune](https://github.com/user-attachments/assets/2d410fc2-5a93-4a6d-8055-136c0351dc6f)

### Logs

Snow unknown error 

### InnerTune version

0.5.11

### Android version

Android 14

### Additional information

![Screenshot_20241128_102842_InnerTune](https://github.com/user-attachments/assets/e995118a-70b5-4981-9008-763df49e48a9)

**Comment by RUDRA78372** [comment] 2024-11-28 05:37
Same on Android 13. Cached/Downloaded songs play, but not anything else.

**Comment by zeeshan0022** [comment] 2024-11-28 06:22
Same Issue

**Comment by Nandkishor01** [comment] 2024-11-28 06:36
Yep Can confirm the issue, even with latest debug version.

**Comment by Dzheremi2** [comment] 2024-11-28 06:48
Seems like it is always `403: forbidden` when trying to access media for playing
![Screenshot_20241128-094709~2.png](https://github.com/user-attachments/assets/9e70b54f-96b1-4978-ab34-f20ca1fb4112)

**Comment by Malopieds** [comment] 2024-11-28 08:17
Duplicate of #410

**Closed as completed** 2024-11-28 08:17 UTC
Labels: bug

**Comment by Sunilr001** [comment] 2024-11-28 09:18
You closed this error, but it's still not playing.

**Comment by Nandkishor01** [comment] 2024-11-28 09:21
> You closed this error, but it's still not playing.

It's a duplicate of [This one](https://github.com/Malopieds/InnerTune/issues/410)

He is working on it so please have patience.
