### ISSUE TITLE
During animations, Queue has no background

### ISSUE THREAD

**Issue by kaneryu** [Malopieds/InnerTune#346] opened 2024-08-25 14:08 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

See video

### Expected behavior

The queue should always have a background, but instead, during an animation it relies on the individual song tiles to have a background

### Actual behavior

See video below
![Video](https://files.catbox.moe/uwscsz.mp4)

### Logs

none

### InnerTune version

0.5.8

### Android version

Android 14

**Comment by kaneryu** [comment] 2024-08-25 14:08
Link to video since that one may not work https://files.catbox.moe/uwscsz.mp4

**Comment by Malopieds** [comment] 2024-08-25 14:16
> I've checked that there is no open or closed issue about this bug.

Duplicate of #337.
Please check for the closed/open issues, it's the second time...

**Closed as completed by Malopieds** 2024-08-25 14:16 UTC
Labels: bug
