### ISSUE TITLE
AMOLED Black background remains in light mode

### ISSUE THREAD

**Issue by kaneryu** [Malopieds/InnerTune#345] opened 2024-08-25 14:02 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Title.

### Expected behavior

AMOLED Black mode should turn off when in light mode (this is referred to as "Pure Black" in the app

### Actual behavior

![Screenshot_20240825_090126_InnerTune](https://github.com/user-attachments/assets/5dec4352-376f-4d8b-ae19-66a545d3db3b)

### Logs

None

### InnerTune version

0.5.8

### Android version

Android 14

**Comment by Malopieds** [comment] 2024-08-25 14:10
Duplicate of #305

**Closed as completed by Malopieds** 2024-08-25 14:10 UTC
Labels: bug
